Repository KakaoTechBC-GOATNINE/kakao_mlms_main, pull requests merged in 2024-09, with the labels that each got.

#3 ✨ swagger-ui 설정 추가
  server/build.gradle
  server/src/main/java/com/example/kakao_mlms/config/OpenApiConfig.java
  server/src/main/java/com/example/kakao_mlms/controller/AdminController.java
  server/src/main/java/com/example/kakao_mlms/controller/AuthController.java
  server/src/main/java/com/example/kakao_mlms/controller/QnaController.java
  server/src/main/java/com/example/kakao_mlms/controller/ReviewController.java
  server/src/main/java/com/example/kakao_mlms/controller/UserController.java
  server/src/main/java/com/example/kakao_mlms/intercepter/UserIdInterceptor.java
  server/src/main/java/com/example/kakao_mlms/security/config/SecurityConfig.java
Labels: documentation, enhancement

#4 ✨ mypage 사용자 정보 출력 및 비밀번호 변경 기능 추가
  frontend/src/App.js
  frontend/src/components/user/Header.jsx
  frontend/src/pages/user/MyPage.jsx
  frontend/src/pages/user/PasswordUpdate.jsx
  server/src/main/java/com/example/kakao_mlms/controller/AuthController.java
  server/src/main/java/com/example/kakao_mlms/domain/User.java
  server/src/main/java/com/example/kakao_mlms/dto/request/UserPasswordDto.java
  server/src/main/java/com/example/kakao_mlms/exception/ErrorCode.java
  server/src/main/java/com/example/kakao_mlms/service/AuthService.java
Labels: bug, documentation

#5 ⚡️ Q&A 답변 삭제 기능 추가
  frontend/src/pages/admin/AdminQnaDetail.jsx
  server/src/main/java/com/example/kakao_mlms/controller/AdminController.java
  server/src/main/java/com/example/kakao_mlms/domain/Answer.java
  server/src/main/java/com/example/kakao_mlms/domain/Qna.java
  server/src/main/java/com/example/kakao_mlms/service/AnswerService.java
  server/src/main/java/com/example/kakao_mlms/service/QnaService.java
Labels: bug, documentation

#6 🐛 닉네임 변경 시 개인정보 페이지의 닉네임은 변경되지 않던 현상 해결 및 비밀번호 변경 UI 수정
  frontend/src/pages/user/MyPage.jsx
  frontend/src/pages/user/PasswordUpdate.jsx
Labels: bug
